# Generated by Django 6.0 on 2025-12-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_customer_birth_data_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
