# Generated by Django 6.0 on 2025-12-17 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_birth_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='birth_data',
            field=models.DateField(),
        ),
    ]
