# Generated by Django 6.0 on 2025-12-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_birth_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birth_data',
            new_name='birth_date',
        ),
    ]
